# Generated by Django 5.2.1 on 2025-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('host', 'Host'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
