# Generated by Django 5.2.1 on 2025-05-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='rooms',
            new_name='number_of_rooms',
        ),
    ]
