# Generated by Django 5.2.1 on 2025-05-23 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('listing', 'user')},
        ),
    ]
