# Generated by Django 5.2.1 on 2025-05-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_date']},
        ),
    ]
